### ISSUE TITLE
使用 search 方法爬取失败

### ISSUE THREAD

**Issue by zbing3** [01ly/DPspider#1]
今天下来使用一下 发现两个问题一个是特别慢 

```
2019-02-20 23:14:56 city(INFO) - 获取 “北京” 地图搜索页成功
2019-02-20 23:14:56 decorator(DEBUG) - <function City.get_map at 0x10a8d26a8> 耗时:67.86s
```
还有就是出现失败

```
2019-02-20 23:15:43 util.http(WARNING) - [失败-403] 重试抓取http://www.dianping.com/search/map/ajax/json 11 次后失败.
```

请问确实还能正常使用么？

**Comment by 01ly** [comment]
原先内置的代理已经过期了，你要用自己的代理

**Comment by 01ly** [comment]
> 今天下来使用一下 发现两个问题一个是特别慢
> 
> ```
> 2019-02-20 23:14:56 city(INFO) - 获取 “北京” 地图搜索页成功
> 2019-02-20 23:14:56 decorator(DEBUG) - <function City.get_map at 0x10a8d26a8> 耗时:67.86s
> ```
> 还有就是出现失败
> 
> ```
> 2019-02-20 23:15:43 util.http(WARNING) - [失败-403] 重试抓取http://www.dianping.com/search/map/ajax/json 11 次后失败.
> ```
> 请问确实还能正常使用么？

原先内置的代理已经过期了，你要用自己的代理

**Comment by janyaaiq** [comment]
> > 今天下来使用一下 发现两个问题一个是特别慢
> > ```
> > 2019-02-20 23:14:56 city(INFO) - 获取 “北京” 地图搜索页成功
> > 2019-02-20 23:14:56 decorator(DEBUG) - <function City.get_map at 0x10a8d26a8> 耗时:67.86s
> > ```
> > 还有就是出现失败
> > ```
> > 2019-02-20 23:15:43 util.http(WARNING) - [失败-403] 重试抓取http://www.dianping.com/search/map/ajax/json 11 次后失败.
> > ```
> > 请问确实还能正常使用么？
> 
> 原先内置的代理已经过期了，你要用自己的代理

遇到了和zbing3一样的问题，我配置好了代理池，测试了代理IP可用。测试beijing.get()和beijing.search()这两个方法时，都是很慢，要等一分多钟才有结果

**Comment by zbing3** [comment]
> > 今天下来使用一下 发现两个问题一个是特别慢
> > ```
> > 2019-02-20 23:14:56 city(INFO) - 获取 “北京” 地图搜索页成功
> > 2019-02-20 23:14:56 decorator(DEBUG) - <function City.get_map at 0x10a8d26a8> 耗时:67.86s
> > ```
> > 还有就是出现失败
> > ```
> > 2019-02-20 23:15:43 util.http(WARNING) - [失败-403] 重试抓取http://www.dianping.com/search/map/ajax/json 11 次后失败.
> > ```
> > 请问确实还能正常使用么？
> 
> 原先内置的代理已经过期了，你要用自己的代理

是的已经配置了自己买的代理池一直是失败

**Comment by 01ly** [comment]
可以加我QQ讨论下1057211448:)

**Comment by nouh** [comment]
请问这个最后是怎么解决的呢，我也有同样的问题
