### ISSUE TITLE
svg加密评论的第一个字无法正常解密

### ISSUE THREAD

**Issue by kanseii** [01ly/DPspider#10]
经过加密的评论的首字无法被正常解密存储

**Comment by 01ly** [comment]
能否把具体问题截图之类的贴上

**Comment by kanseii** [comment]
<img width="768" alt="屏幕快照 2019-04-21 15 28 30" src="https://user-images.githubusercontent.com/26429493/56466886-59e44380-644a-11e9-88c3-d090b5dddec0.png">


![Uploading 屏幕快照 2019-04-21 15.27.12.png…]()


![Uploading 屏幕快照 2019-04-21 15.29.06.png…]()

**Comment by kanseii** [comment]
您好，具体截图已经贴上，请问这是什么原因导致的呢

**Comment by 01ly** [comment]
有没有这个评论的网页源码，看下标签

**Comment by kanseii** [comment]
url：http://www.dianping.com/shop/68166302/review_all/p2
<img width="1026" alt="屏幕快照 2019-04-23 15 15 52" src="https://user-images.githubusercontent.com/26429493/56561928-d312a080-65da-11e9-9c35-063be4fc20fb.png">
大概就是这样的标签 会被过滤掉，无法正常识别
<img width="1121" alt="屏幕快照 2019-04-23 15 21 00" src="https://user-images.githubusercontent.com/26429493/56562174-72d02e80-65db-11e9-9a45-602d365ceaeb.png">

**Comment by 01ly** [comment]
具体解密更新了
