### ISSUE TITLE
加密评论无法解密

### ISSUE THREAD

**Issue by Doveyang** [01ly/DPspider#12]
解密功能好像失效了。
![image](https://user-images.githubusercontent.com/19889990/56634465-af139580-6694-11e9-8ad7-49e493bd6bc8.png)
![image](https://user-images.githubusercontent.com/19889990/56634507-d5393580-6694-11e9-8aaa-5ce5b571c0c5.png)

**Comment by 01ly** [comment]
好的，晚上回去看下

**Comment by 01ly** [comment]
已经更新
