### ISSUE TITLE
评论列表页加密方式更新了，css+svg不适用了

### ISSUE THREAD

**Issue by 3389** [01ly/DPspider#13]
示例页面：http://www.dianping.com/shop/2061139/review_all/p1

标签截图：https://s2.ax1x.com/2019/04/30/EGyfJJ.md.png

现在改的没有特定的class标签了，好像用了新的woff字体加密方式

**Comment by 01ly** [comment]
嗯，解析出woff字体后对应查找uni开头的编码字形信息

**Comment by 01ly** [comment]
已经更新了新的加密解密方法：详见代码库：https://github.com/01ly/Anti-Spider
