### ISSUE TITLE
shop detail url

### ISSUE THREAD

**Issue by Ken2yLiu** [01ly/DPspider#4]
根据shop.py代码可以看到抓取shop信息是在_API_SHOP_这个url，在_setting.py_中设置为_http://www.dianping.com/shop/{id}/review_all_
但是根据实际页面信息，其实在`_API_SHOP_DETAIL  = 'http://www.dianping.com/shop/{id}'_`即可，为什么要进到review_all页面

**Comment by 01ly** [comment]
@Ken2yLiu 因为进去后面那个链接很慢而且标签加密了，需要解密也浪费时间。基本信息前面那个链接已经有了而且是明文。如果要后面那个链接的内容，可以打开后面的链接，通过解密函数解密标签即可获得需要信息。可以看下readme.md的解密那部分。

**Comment by Ken2yLiu** [comment]
@01ly 好的，了解了，然后我发现search/map/经常会跳验证码，目前有什么解决思路么

**Comment by 01ly** [comment]
@Ken2yLiu 换代理是最快的

**Comment by Ken2yLiu** [comment]
@01ly OK, thanks, 请问现在config.py中的参数就是你的默认配置么，主要是关于爬取和重试间隔时间那里
