### ISSUE TITLE
使用的api，报错内容  [无效代理-200] None

### ISSUE THREAD

**Issue by luvm** [01ly/DPspider#5]
开始的时候用的普通代理列表，报错 ‘[无效代理-403] None’ ，然后使用使用的api，报错内容  ‘[无效代理-200] None’

**Comment by 01ly** [comment]
@luvm 证明你的代理没用

**Comment by luvm** [comment]
好快的反馈啊，大佬，我要fllow你，请问api返回的格式是不是也要是'177.84.147.118:44168'，而且是请求一次返回一个？

**Comment by 01ly** [comment]
是的，你可以用代理接口生成一个这个格式的代理返回给程序，程序通过代理接口会生成给requests的可用proxies参数格式的代理
