### ISSUE TITLE
爬取商家，没得电弧号码

### ISSUE THREAD

**Issue by luvm** [01ly/DPspider#6]
武汉张记热干面,,['武汉火车站'], 汉火车北出口,114.42716,30.608599
曾麻子热干面(青城华府店),['027-11'],['余家头'], 城华,114.38802,30.616684
大概爬到的数据是像这样的。。
怎么破

**Comment by 01ly** [comment]
@luvm 因为点评加密标签名改了，修改下源码里的标签名就行了

**Comment by luvm** [comment]
请问是在哪个子文件里面，把啥改成啥呀。。

**Comment by 01ly** [comment]
> 请问是在哪个子文件里面，把啥改成啥呀。。

1.在文件decrypt.py中：函数_get_decrypted里面
```python
 if  not comment:
                svg = {
                    'e':self._str_svg,
                    'd':self._num_svg,
                }[element.name]
                if svg is None:
                    svg = eval(DECRYPT_TAGS[element.name.strip()])(url)
                    {
                        'e': self._str_svg,
                        'd': self._num_svg,
                    }[element.name] = svg
```
改成：
```python
            if  not comment:
                svg = {
                    'bb':self._str_svg,
                    'cc':self._num_svg,
                }[element.name]
                if svg is None:
                    svg = eval(DECRYPT_TAGS[element.name.strip()])(url)
                    {
                        'bb': self._str_svg,
                        'cc': self._num_svg,
                    }[element.name] = svg
```
2.在文件settings.py中，
```python
DECRYPT_TAGS = {
                'd':'_get_num_svg',
                'e':'_get_str_svg',
                'span':'_get_num_svg'
            }
```
改成
```python
DECRYPT_TAGS = {
                'cc':'_get_num_svg',
                'bb':'_get_str_svg',
                'span':'_get_num_svg'
            }
```

**Comment by luvm** [comment]
谢谢您的详细解答！！！


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: linkin <notifications@github.com>
发送时间: Thursday, March 21, 2019 3:36:40 PM
收件人: 01ly/DPspider
抄送: luvm; Mention
主题: Re: [01ly/DPspider] 爬取商家，没得电弧号码 (#6)


请问是在哪个子文件里面，把啥改成啥呀。。

1.在文件decrypt.py中：函数_get_decrypted里面

 if  not comment:

                svg = {

                    'e':self._str_svg,

                    'd':self._num_svg,

                }[element.name]

                if svg is None:

                    svg = eval(DECRYPT_TAGS[element.name.strip()])(url)

                    {

                        'e': self._str_svg,

                        'd': self._num_svg,

                    }[element.name] = svg

改成：

            if  not comment:

                svg = {

                    'bb':self._str_svg,

                    'cc':self._num_svg,

                }[element.name]

                if svg is None:

                    svg = eval(DECRYPT_TAGS[element.name.strip()])(url)

                    {

                        'bb': self._str_svg,

                        'cc': self._num_svg,

                    }[element.name] = svg

2.在文件settings.py中，

DECRYPT_TAGS = {

                'd':'_get_num_svg',

                'e':'_get_str_svg',

                'span':'_get_num_svg'

            }

改成

DECRYPT_TAGS = {

                'cc':'_get_num_svg',

                'bb':'_get_str_svg',

                'span':'_get_num_svg'

            }

―

**Comment by 01ly** [comment]
主要就是标签名的改变，如果后续还有改动，可以参照这样修改
